begin
  UPDATE ENTRY_RELATION
  SET CURRENT_FINE = 100 * FINE_RATE + CURRENT_FINE, ACCUMULATE_DAY = ACCUMULATE_DAY + 2
  WHERE TRUNC(ACCUMULATE_DAY) = TRUNC(SYSDATE + INTERVAL '7' HOUR) ;

  UPDATE ENTRY_RELATION
  SET E_STATUS = 'Late', CURRENT_FINE = CURRENT_FINE + 100
  WHERE TRUNC(DEADLINE) = TRUNC(SYSDATE + INTERVAL '7' HOUR) AND E_STATUS = 'In Borrow'; 
end;