SELECT ENTRY_ID,
  EMAIL,
  BOOK_ID,
  TITLE,
  B_CATEGORY,
  dbms_lob.getlength(BOOK_PICTURE) AS BOOK_PICTURE,
  FILENAME,
  MIMETYPE,
  CURRENT_FINE,
  DEADLINE,
  ACCUMULATE_DAY,
  NULL AS RETURN_ACTION
FROM USER_BOOK_VIEW
WHERE UPPER(EMAIL) = V('APP_USER');