FUNCTION CUSTOM_AUTH (p_username IN VARCHAR2, p_password IN VARCHAR2) RETURN BOOLEAN AS my_user NUMBER := 0;
BEGIN
SELECT 1 INTO my_user
FROM USER_ENTITY
WHERE UPPER(EMAIL) = UPPER(p_username)
  AND u_password = p_password;
RETURN TRUE;
EXCEPTION
WHEN NO_DATA_FOUND THEN RETURN FALSE;
END CUSTOM_AUTH;