SELECT TITLE,
  COUNT(TITLE) AS VALUE,
  CONCAT(
    'Users: ',
    LISTAGG(EMAIL, ', ') WITHIN GROUP (
      ORDER BY EMAIL
    )
  ) AS TOOLTIP
FROM ENTRY_RELATION
WHERE TITLE IS NOT NULL
GROUP BY TITLE;